-- Создание таблицы
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  dateTime timestamp with time zone not null,
  name text not null
);

-- Разрешить чтение и добавление для всех (anon)
alter table public.bookings enable row level security;

create policy "Allow read"
  on public.bookings
  for select
  to anon
  using (true);

create policy "Allow insert"
  on public.bookings
  for insert
  to anon
  with check (true);